version: "3.5"

services:
  jenkins1:
    image: jenkins/jenkins:2.235-alpine
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"
    volumes:
      - "./data1:/var/jenkins_home"
    ports:
      - "8085:8080"

  jenkins2:
    image: jenkins/jenkins:2.235-alpine
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"
    volumes:
      - "./data2:/var/jenkins_home"
    ports:
      - "8086:8080"
